version: "3"

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rabab-12
      MONGO_INITDB_ROOT_PASSWORD: Rr1993
    ports:
      - mongodb+srv://rabab-12:Rr1993@cluster0.eagvv.mongodb.net/writer-feather?retryWrites=true&w=majority
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: rabab-12
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: Rr1993
  #     ME_CONFIG_MONGODB_URL: mongodb://rabab-12:Rr1993@mongo:27017/
  writer-feather:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /Desktop/writer-feather
    environment:
      - DB=mongodb+srv://rabab-12:Rr1993@cluster0.eagvv.mongodb.net/writer-feather?retryWrites=true&w=majority
    ports:
      - 4500:4500
    depends_on:
      - "mongo"
